---
- name: stop netmon-scanner service
  ansible.builtin.service:
    name: netmon-scanner.service
    state: stopped
  failed_when: false
  become: true

- name: copy bash files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ package_dir }}/{{ item | basename }}"
    force: true
  with_fileglob:
    - files/*.bash
  become: true

- name: gather distribution_release
  ansible.builtin.setup: { gather_subset: [ "!all", "!min", "distribution_release" ] }

- name: install dependencies
  ansible.builtin.apt:
    name:
      - dnsutils
      - nmap
      - "{{ 'openjdk-8-jre' if 'buster' in ansible_distribution_release else 'default-jdk' }}"
    state: present
  become: true

- name: add capabilities to nmap to allow rootless scanning
  import_tasks: nmap-capabilities.yml

- name: compute netmon_scanner_service defaults
  ansible.builtin.set_fact:
    netmon_scanner_service: >
      {{
      netmon_scanner_service | default({})
      | combine({'user': ansible_facts.user_id})
      | combine({'working_directory': ansible_facts.user_dir ~ '/netmon'})
      }}
  when: netmon_scanner_service is undefined

- name: build java args
  ansible.builtin.set_fact:
    netmon_scanner_java_args: >
      {{
      (netmon_scanner_java_args | default([])) + ['-D' + (item.key|string) + '="' + (item.value|string) + '"']
      }}
  with_dict: "{{ netmon_scanner_args }}"

- name: copy service
  ansible.builtin.template:
    src: templates/netmon-scanner.service.j2
    dest: /etc/systemd/system/netmon-scanner.service
    mode: "0644"
    force: true
  become: true

- name: enable netmon-scanner service
  ansible.builtin.systemd_service:
    name: netmon-scanner.service
    daemon_reload: true
    enabled: true
  become: true

- name: build artifact if necessary
  local_action:
    module: ansible.builtin.shell
    chdir: "{{ project_dir }}"
    cmd: "./gradlew --no-daemon clean shadowJar"
    creates: "{{ netmon_scanner_build_artifact }}"
  run_once: True

- name: copy artifact
  ansible.posix.synchronize:
    src: "{{ netmon_scanner_build_artifact }}/"
    dest: "{{ package_dir }}/netmon-scanner/"
  become: true

- name: restart netmon-scanner service
  ansible.builtin.systemd_service:
    name: netmon-scanner.service
    state: restarted
  become: true
