---
- name: install dependencies
  ansible.builtin.apt:
    name: [ dnsutils, nmap, openjdk-8-jre ]
    state: present
  become: true

- name: compute netmon_scanner_service defaults
  set_fact:
    netmon_scanner_service: >
      {{
      netmon_scanner_service | default({})
      | combine({'user': ansible_facts.user_id})
      | combine({'working_directory': ansible_facts.user_dir ~ '/netmon'})
      }}
  when: netmon_scanner_service is undefined

- name: build java args
  set_fact:
    netmon_scanner_java_args: >
      {{
      (netmon_scanner_java_args | default([])) + ['-D' + (item.key|string) + '="' + (item.value|string) + '"']
      }}
  with_dict: "{{ netmon_scanner_args }}"

- name: copy service
  become: true
  ansible.builtin.template:
    src: templates/netmon-scanner.service.j2
    dest: /etc/systemd/system/netmon-scanner.service
    mode: "0644"
    force: true

- name: enable service
  become: true
  ansible.builtin.systemd_service:
    name: netmon-scanner.service
    daemon_reload: true
    enabled: true

- name: build artifact if necessary
  local_action:
    module: ansible.builtin.shell
    chdir: "{{ project_dir }}"
    cmd: "./gradlew --no-daemon clean shadowJar"
    creates: "{{ netmon_scanner_build_artifact }}"
  run_once: True

- name: copy artifact
  become: true
  ansible.builtin.copy:
    src: "{{ netmon_scanner_build_artifact }}/"
    dest: "{{ package_dir }}/netmon-scanner/"
    force: true

- name: restart service
  become: true
  ansible.builtin.systemd_service:
    name: netmon-scanner.service
    state: restarted
