---
# needed on outdated systems, for dependencies to be installable
- name: update apt packages and allow release info changes
  block:
    - name: configure apt to allow release info change
      become: true
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/99allow-release-info-change
        state: present
        create: yes
        line: Acquire::AllowReleaseInfoChange::Suite "true";
    - name: update apt packages
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400

- name: install dependencies
  ansible.builtin.apt:
    name: [ dnsutils, nmap, openjdk-8-jre ]
    state: present
  become: true

- name: compute netmon_scanner_service defaults
  set_fact:
    netmon_scanner_service: >
      {{
      netmon_scanner_service | default({})
      | combine({'user': ansible_facts.user_id})
      | combine({'working_directory': ansible_facts.user_dir ~ '/netmon'})
      }}
  when: netmon_scanner_service is undefined

- name: copy service
  become: true
  ansible.builtin.template:
    src: templates/netmon-scanner.service.j2
    dest: /etc/systemd/system/netmon-scanner.service
    mode: "0644"
    force: true

- name: enable service
  become: true
  ansible.builtin.systemd_service:
    name: netmon-scanner.service
    daemon_reload: true
    enabled: true

- name: build artifact if necessary
  local_action:
    module: ansible.builtin.shell
    chdir: "{{ project_dir }}"
    cmd: "./gradlew --no-daemon clean shadowJar"
    creates: "{{ netmon_scanner_build_artifact }}"
  run_once: True

- name: copy artifact
  become: true
  ansible.builtin.copy:
    src: "{{ netmon_scanner_build_artifact }}/"
    dest: "{{ package_dir }}/netmon-scanner/"

- name: restart service
  become: true
  ansible.builtin.systemd_service:
    name: netmon-scanner.service
    state: restarted
