version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
    groups:
      gradle:
        patterns: ["*"]
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: monthly
