#!/bin/bash

./gradlew runReleaseExecutableNativeRemotely -PnativeTarget=linuxX64

#./gradlew linkReleaseExecutableNative -PnativeTarget=linuxArm32Hfp
#scp build/bin/native/releaseExecutable/netmon.kexe bkahlert@unicorn-hd.local:/home/bkahlert/ 1>/dev/null
#ssh bkahlert@unicorn-hd.local './netmon.kexe'
