---
- name: uninstall x11vnc
  block:
    - name: disable x11vnc.service
      ansible.builtin.systemd:
        name: x11vnc.service
        state: stopped
        enabled: no
      become: true
      failed_when: false
      no_log: true
    - name: remove x11vnc.service unit
      ansible.builtin.file:
        path: /etc/systemd/system/x11vnc.service
        state: absent
      become: true
    - name: remove package
      ansible.builtin.apt:
        name: [ x11vnc ]
        state: absent
        autoremove: true
      become: true
    - name: remove .vnc directory
      ansible.builtin.file:
        path: /home/pi/.vnc
        state: absent
      become: true

- name: uninstall lighttpd
  block:
    - name: disable lighttpd.service
      ansible.builtin.systemd:
        name: lighttpd.service
        state: stopped
        enabled: no
      become: true
      failed_when: false
      no_log: true
    - name: remove lighttpd
      ansible.builtin.apt:
        name: [ lighttpd ]
        state: absent
      become: true
      notify: "restart lightdm"
    - name: remove /var/www/html
      ansible.builtin.file:
        path: /var/www/html
        state: absent
      become: true

- name: undo wpa_supplicant symlink
  vars:
    wpas_conf: /etc/wpa_supplicant/wpa_supplicant.conf
  block:
    - name: check if {{ wpas_conf }} is a symlink
      ansible.builtin.stat: { path: "{{ wpas_conf }}" }
      register: wpa_supplicant_conf

    - name: determine symlink target
      ansible.builtin.command: readlink -f '{{ wpas_conf }}'
      register: wpa_supplicant_conf_symlink_target
      changed_when: false
      when: wpa_supplicant_conf.stat.islnk

    - name: move symlink target back to {{ wpas_conf }}
      become: true
      ansible.builtin.command: mv '{{ wpa_supplicant_conf_symlink_target.stdout }}' '{{ wpas_conf }}'
      when: wpa_supplicant_conf.stat.islnk and wpa_supplicant_conf_symlink_target.stdout != ''

    - name: fix permissions of {{ wpas_conf }}
      become: true
      ansible.builtin.file:
        path: '{{ wpas_conf }}'
        owner: root
        group: root
        mode: '0600'
      when: wpa_supplicant_conf.stat.islnk and wpa_supplicant_conf_symlink_target.stdout != ''

- name: remove FullPageOS config files
  become: true
  shell: "rm -rf /boot/fullpage*"
