#!/bin/bash

# Important: If you run into problems, you can always switch to a TTY with
# Ctrl+Alt+F2 (Ctrl+Alt+Fn+F2 on some keyboards)

LOG_FILE=/tmp/netmon-kiosk.log
printf 'LOG STARTED %s\n' "$(date)" >"$LOG_FILE"

tweak_ui() {
    printf "Setting background... "
    xsetroot -solid black && printf '\e[32m✔︎\e[0m\n'

    printf "Disabling screensaver... "
    xset s off && printf '\e[32m✔︎\e[0m\n'

    printf "Disabling DPMS / Energy Star features... "
    xset -dpms && printf '\e[32m✔︎\e[0m\n'

    printf "Disabling screen blanking... "
    xset s noblank && printf '\e[32m✔︎\e[0m\n'

    printf "Moving mouse pointer to top-left corner to not trigger hover styles... "
    xdotool mousemove 0 0 && printf '\e[32m✔︎\e[0m\n'

    printf "Hiding mouse pointer... "
    pgrep -a unclutter >/dev/null || (unclutter -idle 0 -root &) && printf '\e[32m✔︎\e[0m\n'
}

enhance_visual_rendering() {
    local compton_args=(
        -d "$DISPLAY"                # display to be managed
        --daemon                     # fork to background after initialization
        --unredir-if-possible        # un-redirect all windows if a full-screen opaque window is detected, to maximize performance for full-screen windows
        --paint-on-overlay           # painting on X Composite overlay window instead of on root window
        --vsync opengl               # try to VSync with SGI_video_sync OpenGL extension
        --backend glx                # perform all back-end rendering operations with OpenGL
        --glx-no-stencil             # avoid using stencil buffer
        --glx-swap-method buffer-age # assume auto-detection using GLX_EXT_buffer_age as GLX buffer swap method
    )
    compton "${compton_args[@]}"
}

open_chromium() {
    local URL=${1?URL missing}
    local chromium_args=(
        --app="$URL"
        --autoplay-policy=no-user-gesture-required
        --disable-pinch
        --disable-session-crashed-bubble
        --disable-component-update
        --disable-features=TranslateUI
        --kiosk
        --noerrdialogs
        --overscroll-history-navigation=0
        --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT'
        --touch-events=enabled
    )
    set -x
    chromium-browser "${chromium_args[@]}"
}

finalize_chromium() {
    local visible_wid visible_wname
    printf "Waiting for the Chromium window to become visible... "
    while ! visible_wid=$(xdotool search --sync --onlyvisible --class chromium 2>/dev/null); do
        sleep 1
    done
    visible_wname=$(xdotool getwindowname "$visible_wid")
    printf '\e[32m✔︎\e[0m wid: %s, name: %s\n' "$visible_wid" "$visible_wname"

    while read -r wid; do
        if [ "$wid" = "$visible_wid" ]; then
            # printf 'Hiding Chromium window %s...' "$wid"
            # xdotool windowunmap "$wid" && printf '\e[32m✔︎\e[0m\n'
            printf "Activating Chromium window %s... " "$visible_wid"
            xdotool windowactivate "$visible_wid" && printf '\e[32m✔︎\e[0m\n'
            #        else
            #            printf 'Closing invisible Chromium window %s...' "$wid"
            #            xdotool windowclose "$wid" && printf '\e[32m✔︎\e[0m\n'
        fi
    done < <(xdotool search --class chromium)

    printf "Sending F11 key to switch Chromium window %s to full-screen mode... " "$visible_wid"
    xdotool key F11 && printf '\e[32m✔︎\e[0m\n'

    printf "Waiting for Chromium window %s to update its title... " "$visible_wid"
    while [ "$(xdotool getwindowname "$visible_wid")" = "$visible_wname" ]; do
        sleep 1
    done
    printf '\e[32m✔︎\e[0m\n'

    # printf "Un-hiding Chromium window %s... " "$visible_wid"
    # xdotool windowmap "$visible_wid" && printf '\e[32m✔︎\e[0m\n'

}

export DISPLAY=:0

tweak_ui >>"$LOG_FILE" 2>&1
enhance_visual_rendering
open_chromium "${NETMON_KIOSK_URL:-http://localhost/}" >>"$LOG_FILE" 2>&1 &
finalize_chromium >>"$LOG_FILE" 2>&1 &
exec matchbox-window-manager -use_titlebar no
