---
- name: cleanup FullPageOS
  block:
    - name: uninstall x11vnc
      block:
        - name: disable x11vnc.service
          ansible.builtin.systemd:
            name: x11vnc.service
            state: stopped
            enabled: no
          become: true
          failed_when: false
          no_log: true
        - name: remove x11vnc.service unit
          ansible.builtin.file:
            path: /etc/systemd/system/x11vnc.service
            state: absent
          become: true
        - name: remove package
          ansible.builtin.apt:
            name: [ x11vnc ]
            state: absent
            autoremove: true
          become: true
        - name: remove .vnc directory
          ansible.builtin.file:
            path: /home/pi/.vnc
            state: absent
          become: true

    - name: uninstall lighttpd
      block:
        - name: disable lighttpd.service
          ansible.builtin.systemd:
            name: lighttpd.service
            state: stopped
            enabled: no
          become: true
          failed_when: false
          no_log: true
        - name: remove lighttpd
          ansible.builtin.apt:
            name: [ lighttpd ]
            state: absent
            autoremove: true
          become: true
          notify: "restart lightdm"
        - name: remove /var/www/html
          ansible.builtin.file:
            path: /var/www/html
            state: absent
          become: true


- name: fix FullPageOS
  notify: "restart lightdm"
  block:
    - name: symlink the home directory of ansible_user to the home directory of pi
      # this might be necessary if the username was changed
      ansible.builtin.file:
        src: "{{ ansible_facts.user_dir }}"
        dest: /home/pi
        state: link
      become: true
      when: ansible_facts.user_id != 'pi'

- name: configure FullPageOS
  notify: "restart lightdm"
  block:
    # alternative would be to replace /home/pi/scripts/get_url
    - name: set URL
      ansible.builtin.copy:
        content: "{{ netmon_web_display_url }}"
        dest: /boot/fullpageos.txt
      become: true
