---
- name: disable overscan
  become: true
  community.general.ini_file:
    path: /boot/config.txt
    no_extra_spaces: true
    section: ''
    option: disable_overscan
    value: '1'
  notify: reboot

- name: configure HDMI
  become: true
  community.general.ini_file:
    path: /boot/config.txt
    no_extra_spaces: true
    section: ''
    option: "hdmi_{{ item.key }}"
    value: "{{ item.value }}"
    mode: "0644"
  loop: "{{ hdmi | dict2items }}"
  when: hdmi is defined
  notify: reboot

- name: remove gpu_mem setting
  become: true
  community.general.ini_file:
    path: /boot/config.txt
    no_extra_spaces: true
    section: 'all'
    option: gpu_mem
    state: absent
  notify: reboot

- name: disable vc4-kms-v3d overlay for custom resolution
  # this overlay causes problems together with custom resolution
  # see https://github.com/raspberrypi/linux/issues/4516
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    regexp: '^dtoverlay=vc4-kms-v3d'
    state: absent
  become: true
  when: hdmi is defined and hdmi.group|string == '2' and hdmi.mode|string == '87'
  notify: reboot

- name: enable display_auto_detect
  become: true
  community.general.ini_file:
    path: /boot/config.txt
    no_extra_spaces: true
    section: 'all'
    option: display_auto_detect
    value: '1'
  notify: reboot
