#!/bin/bash

# Important: If you run into problems, you can always switch to a TTY with
# Ctrl+Alt+F2 (Ctrl+Alt+Fn+F2 on some keyboards)

LOG_FILE=/tmp/netmon-kiosk.log
printf 'LOG STARTED %s\n' "$(date)" >"$LOG_FILE"

tweak_ui() {
    printf "Disabling screensaver... "
    xset s off && printf '\e[32m✔︎\e[0m\n'

    printf "Disabling DPMS / Energy Star features... "
    xset -dpms && printf '\e[32m✔︎\e[0m\n'

    printf "Disabling screen blanking... "
    xset s noblank && printf '\e[32m✔︎\e[0m\n'

    printf "Moving mouse pointer to top-left corner to not trigger hover styles... "
    xdotool mousemove 0 0 && printf '\e[32m✔︎\e[0m\n'

    printf "Hiding inactive mouse pointer... "
    unclutter -root &
    if [ $? -eq 0 ]; then
        printf '\e[32m✔︎\e[0m\n'
    else
        printf '\e[31m✘\e[0m\n'
    fi
}

enhance_visual_rendering() {
    local compton_args=(
        -d "$DISPLAY"                # display to be managed
        --daemon                     # fork to background after initialization
        --unredir-if-possible        # un-redirect all windows if a full-screen opaque window is detected, to maximize performance for full-screen windows
        --paint-on-overlay           # painting on X Composite overlay window instead of on root window
        --vsync opengl               # try to VSync with SGI_video_sync OpenGL extension
        --backend glx                # perform all back-end rendering operations with OpenGL
        --glx-no-stencil             # avoid using stencil buffer
        --glx-swap-method buffer-age # assume auto-detection using GLX_EXT_buffer_age as GLX buffer swap method
    )
    compton "${compton_args[@]}"
}

open_chromium() {
    local URL=${1?URL missing}
    local chromium_args=(
        --kiosk
        --touch-events=enabled
        --disable-pinch
        --noerrdialogs
        --disable-session-crashed-bubble
        --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT'
        --disable-component-update
        --overscroll-history-navigation=0
        --disable-features=TranslateUI
        --app="$URL"
    )
    chromium-browser "${chromium_args[@]}"
}

finalize_chromium() {
    local visible_wid
    printf "Waiting for the Chromium window to become visible... "
    while ! visible_wid=$(xdotool search --sync --onlyvisible --class chromium); do
        sleep 1
    done
    printf '\e[32m✔︎\e[0m wid=%s\n' "$visible_wid"

    while read -r wid; do
        if [ ! "$wid" = "$visible_wid" ]; then
            printf 'Closing invisible window %s...' "$wid"
            xdotool windowclose "$wid" && printf '\e[32m✔︎\e[0m\n'
        fi
    done < <(xdotool search --class chromium)

    printf "Activating Chromium window %s... " "$visible_wid"
    xdotool windowactivate "$visible_wid" && printf '\e[32m✔︎\e[0m\n'

    printf "Sending F11 key to switch Chromium window %s to full-screen mode... " "$visible_wid"
    xdotool key F11 && printf '\e[32m✔︎\e[0m\n'
}

export DISPLAY=:0

tweak_ui >>"$LOG_FILE" 2>&1
enhance_visual_rendering
open_chromium 'http://localhost/?broker.port=8080' &
finalize_chromium >>"$LOG_FILE" 2>&1 &
exec matchbox-window-manager
