---
all:
  hosts:
    # Device "foo" with default configuration, that is: `ws://test.mosquitto.org:8080`
    foo.local:

    # Device "bar" with an automatically installed Mosquitto broker and custom HDMI settings
    bar.local:
      # optional: Add your Pi Hero configuration here, see https://github.com/bkahlert/pihero
      broker: { host: localhost, port: 8080, install: true }
      hdmi: { group: 2, mode: 87, cvt: 800 480 60 6 0 0 0, drive: 1 } # HAMTYSAN 7-inch display
