---
all:
  hosts:
    # Device "foo" no default configuration
    foo.local:

    # Device "bar" with custom HDMI settings
    bar.local:
      # optional: Add your Pi Hero configuration here, see https://github.com/bkahlert/pihero
      hdmi: { group: 2, mode: 87, cvt: 800 480 60 6 0 0 0, drive: 1 } # HAMTYSAN 7-inch display
