#!/usr/bin/env bash

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

PROJECT_DIR=${PROJECT_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}    # The project root directory (default: parent directory of this script)
GRADLE_NO_DAEMON=${GRADLE_NO_DAEMON:-1}                      # Whether to run Gradle without daemon for building (default: yes)
GRADLE_CLEAN=${GRADLE_CLEAN:-1}                              # Whether to clean Gradle build directory before building (default: yes)
GRADLE_EXE=${GRADLE_EXE:-$PROJECT_DIR/gradlew}               # The Gradle executable to use for building (default: Gradle wrapper)
GRADLE_WORKING_DIR=${GRADLE_WORKING_DIRECTORY:-$PROJECT_DIR} # The working directory for Gradle (default: project root)

PREFIX=${PATCH_PREFIX-NETMON_}
# Sets variable with name $1 to the value of variable $PREFIX_$1 if it exists.
# If it doesn't, uses $2 as the default value or exits with an error message.
p() {
    local var=${1?var missing} && shift
    local default=$1
    local prefixed=$PREFIX$var
    local resolved=${!prefixed}
    if [ "$resolved" ]; then
        printf -v "$var" '%s' "$resolved"
    elif [ "$default" ]; then
        printf -v "$var" '%s' "$default"
    else
        printf '\e[31mRequired parameter \e[3m%s\e[23m is missing.\e[0m\n' "$prefixed" >&2
        printf 'Either use \e[3m%s\e[23m or run \e[3m%s\e[23m to provide it.\n' "export $prefixed=..." "$prefixed=... ${0##*/}"
        exit 1
    fi
    printf -v "$var" '%s' "${!prefixed:-$default}"
}

# Parameters
p HOST                                               # The host to patch
p MAIN 1                                             # Whether to update the netmon entrypoint
p MAIN_FILES "$SCRIPT_DIR/roles/netmon/files"        # The directory containing the bin and lib directory of the netmon entrypoint
p SCANNER 0                                          # Whether to build und update the scanner component
p WEB_DISPLAY 0                                      # Whether to build und update the web display component
p KIOSK 0                                            # Whether to update the kiosk component
p KIOSK_FILES "$SCRIPT_DIR/roles/netmon_kiosk/files" # The directory containing the files of the kiosk component

if [ "$MAIN" = 0 ] && [ "$SCANNER" = 0 ] && [ "$WEB_DISPLAY" = 0 ] && [ "$KIOSK" = 0 ]; then
    printf -v params '\e[3m%s\e[23m ' "${PREFIX}HOST=foo.local" "$PREFIX...=..."
    printf '\e[1mUsage: %s %s\e[0m\n' "$params" "${0##*/}"
    printf ' Hint: Type export %sto set a different host and the appropriate option or options for the remainder of your shell session.\n' "$params"
    printf '       Check the source code for more options.\n'
    exit 1
fi

# Ansible ad-hoc command wrapper which runs:
# ansible $HOST --become -m $1 -a "$2 $3 $4 ..."
m() {
    local module=${1?module missing} && shift
    local args="$*"
    ansible "$HOST" --become -m "$module" -a "$args"
}

# rsync command wrapper which runs:
# rsync --recursive --compress --delete --rsh='ssh -o ConnectTimeout=120' --rsync-path='sudo rsync' "${@:1:$#-1}" "$HOST:${@: -1}"
r() {
    [ "$#" -ge 2 ] || {
        printf '\e[31mAt least two parameters—the files to copy, and the destination—are required\n'
        exit 1
    }
    local src=("${@:1:$#-1}")
    local dst="$HOST:${@: -1}"
    printf "Copying \e[3m%s\e[23m to \e[3m%s\e[23m... " "${src[*]}" "$dst"
    rsync --recursive --compress --delete --rsh='ssh -o ConnectTimeout=10' --rsync-path='sudo rsync' "${src[@]}" "$dst" || {
        printf '\e[31Failed to copy \e[3m%s\e[23m to \e[3m%s\e[23m\n' "$src" "$dst"
        exit 1
    }
    printf '\e[32m✔︎\e[0m\n'
}

# build
declare gradle_success=0
if [ ! "$SCANNER" = 0 ] || [ ! "$WEB_DISPLAY" = 0 ]; then
    gradle_args=()
    [ "$GRADLE_NO_DAEMON" = 0 ] || gradle_args+=(--no-daemon)
    [ "$GRADLE_CLEAN" = 0 ] || gradle_args+=(clean)
    [ "$SCANNER" = 0 ] || gradle_args+=(shadowJar)
    [ "$WEB_DISPLAY" = 0 ] || gradle_args+=(jsBrowserProductionWebpack)

    if (
        cd "$GRADLE_WORKING_DIR" || exit 1
        "$GRADLE_EXE" "${gradle_args[@]}"
    ); then
        gradle_success=1
    fi
fi

# deploy scanner component
if [ "$gradle_success" = 1 ] && [ ! "$SCANNER" = 0 ]; then
    m ansible.builtin.service name=netmon-scanner state=stopped
    r "$PROJECT_DIR/build/libs/" /opt/netmon/netmon-scanner/
    m ansible.builtin.service name=netmon-scanner state=restarted
fi

# deploy web display component
if [ "$gradle_success" = 1 ] && [ ! "$WEB_DISPLAY" = 0 ]; then
    r "$PROJECT_DIR/build/dist/js/productionExecutable/" /opt/netmon/netmon-web-display/
    m ansible.builtin.shell 'export DISPLAY=:0 && wid=$(xdotool search --sync --onlyvisible --class chromium | head -1) && xdotool windowactivate "$wid" && xdotool key ctrl+F5 && xdotool key F11 || printf "Failed to find Chromium window\n"'
fi

# deploy netmon entrypoint
if [ ! "$MAIN" = 0 ]; then
    r "$MAIN_FILES/bin/netmon" /opt/netmon/bin/netmon
    r "$MAIN_FILES/lib/" /opt/netmon/lib/
fi

# deploy kiosk component
if [ ! "$KIOSK" = 0 ]; then
    r "$KIOSK_FILES/netmon-kiosk" /opt/netmon/bin/netmon-kiosk
    m ansible.builtin.service name=display-manager state=restarted
fi
