---
- hosts: "{{ inventory if inventory is defined else 'all' }}"
  gather_facts: false
  tags: [ always ]
  tasks:
    - name: make sure services {{ temporarily_disabled_services | join(', ') }} are stopped
      ansible.builtin.service: { name: "{{ item }}", state: stopped }
      loop: "{{ temporarily_disabled_services | reverse }}"
      become: true
      failed_when: false
      no_log: true

- name: run Pi Hero playbook, if --tags pihero is specified
  ansible.builtin.import_playbook: ../../pihero/playbook.yml
  tags: [ never, pihero ]

- hosts: "{{ inventory if inventory is defined else 'all' }}"
  gather_facts: false
  max_fail_percentage: 0
  tags: [ always ]

  pre_tasks:
    - name: gather user facts
      ansible.builtin.setup: { gather_subset: [ "!all", "!min", "user_dir", "user_id" ] }
    - name: update apt packages and allow release info changes
      import_tasks: tasks/apt-update.yml

  post_tasks:
    - name: make sure services {{ temporarily_disabled_services | join(', ') }} are started
      ansible.builtin.service: { name: "{{ item }}", state: started }
      loop: "{{ temporarily_disabled_services }}"
      become: true

  roles:
    - hdmi               # configures Kernel HDMI settings
    - mosquitto          # installs the MQTT broker Eclipse Mosquitto
    - netmon             # installs the entrypoint
    - netmon_kiosk       # configures X11-based kiosk mode
    - netmon_scanner     # installs the scan component
    - netmon_web_display # installs the HTML-based display component
