---
- name: run Pi Hero playbook, if --tags pihero is specified
  ansible.builtin.import_playbook: ../../pihero/playbook.yml
  tags: [ never, pihero ]

- hosts: "{{ inventory if inventory is defined else 'all' }}"
  gather_facts: false
  max_fail_percentage: 0
  tags: [ netmon ]

  pre_tasks:
    - name: gather user facts
      ansible.builtin.setup: { gather_subset: [ "!all", "!min", "user_dir", "user_id" ] }
    - name: update apt packages and allow release info changes
      import_tasks: tasks/apt-update.yml

  roles:
    # installs the MQTT broker Eclipse Mosquitto
    - role: mosquitto
      tags: [ mosquitto ]
    # installs the CLI component
    - role: netmon
      tags: [ netmon-cli ]
    # installs the scan component
    - role: netmon_scanner
      tags: [ netmon-scanner ]
    # configures X11-based kiosk mode
    - role: netmon_kiosk
      tags: [ netmon-kiosk ]
    # installs the HTML-based display component
    - role: netmon_web_display
      tags: [ netmon-web-display ]
    # increases swap for Chromium
    - role: geerlingguy.swap
      become: true
      tags: [ swap ]
