---
- name: warn if broker is set to install but host is not localhost
  when: broker.install | default(false) and broker.host != 'localhost'
  ansible.builtin.debug:
    msg: |
      Mosquitto MQTT broker will be installed, but broker.host is set to "{{ broker.host }}" instead of "localhost".
      If this is not what you want, please change broker.host to "localhost" or disable broker.install.

- name: install Mosquitto
  when: broker.install | default(false)
  import_tasks: tasks/mosquitto.yml
