---
- name: copy bash files
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ package_dir }}/{{ item | basename }}"
    force: true
  with_fileglob:
    - files/*.bash

- name: install dependencies
  ansible.builtin.apt:
    name:
      - fonts-dejavu              # font family with good unicode support; lowers the chance of seeing boxes instead of characters
      - fonts-dejavu-extra        # font family with good unicode support; lowers the chance of seeing boxes instead of characters even more
      - fonts-noto                # coverage bazooka; covers a lot of unicode characters
      - ttf-mscorefonts-installer # font like Times and Verdana
      - lightdm                   # display manager
      - accountsservice           # lightdm dependency
      - x11-xserver-utils         # xset and xsetroot
      - xdotool                   # for mouse manipulation
      - unclutter                 # hides the mouse cursor
      - matchbox-window-manager   # window manager
      - upower                    # if missing, causes error messages like the following when running Chromium:
      # Failed to call method: org.freedesktop.DBus.Properties.Get: ↵
      # object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: ↵
      # The name org.freedesktop.UPower was not provided by any .service files
      - chromium-browser          # displays the web application
    state: present
  become: true

- name: compute netmon_kiosk defaults
  set_fact:
    netmon_kiosk: >
      {{
      netmon_kiosk | default({})
      | combine({'user': ansible_facts.user_id})
      }}
  when: netmon_kiosk is undefined

- name: copy netmon-kiosk
  become: true
  ansible.builtin.copy:
    src: files/netmon-kiosk
    dest: "{{ package_dir }}/bin/netmon-kiosk"
    mode: "0755"
    force: true

- name: copy netmon-kiosk.desktop
  become: true
  ansible.builtin.template:
    src: templates/netmon-kiosk.desktop.j2
    dest: "/usr/share/xsessions/{{ lightdm_user_session }}.desktop"
    mode: "0644"
    force: true

- name: configure lightdm to use netmon session
  become: true
  community.general.ini_file:
    path: /etc/lightdm/lightdm.conf
    no_extra_spaces: true
    section: "Seat:*"
    option: "user-session"
    value: "{{ lightdm_user_session }}"

- name: configure lightdm to use auto-login {{ netmon_kiosk.user }}
  become: true
  community.general.ini_file:
    path: /etc/lightdm/lightdm.conf
    no_extra_spaces: true
    section: "Seat:*"
    option: "autologin-user"
    value: "{{ netmon_kiosk.user }}"

- name: enable lightdm service
  become: true
  ansible.builtin.systemd_service:
    name: lightdm.service
    daemon_reload: true
    enabled: true

- name: set default target to graphical
  become: true
  ansible.builtin.shell: systemctl set-default graphical.target
