Args = -H:Class=com.bkahlert.netmon.scanner.app.Application \
       --no-fallback \
       -march=compatibility \
       --install-exit-handlers \
       -R:MaxHeapSize=64m \
       --enable-url-protocols=http,https
